services:
  consul:
    image: consul:1.15
    container_name: consul
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - service-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 3

  consul-kv-init:
    image: consul:1.15
    container_name: consul-kv-init
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - service-network
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    entrypoint:
      - "sh"
      - "-c"
      - |
        sleep 5
        consul kv put hazelcast/cluster_members '[" #:5701"," #:5702"," #:5703"]'
        consul kv put mq/bootstrap_servers "kafka-1:9092,kafka-2:9092,kafka-3:9092"
        consul kv put mq/topic "messages"
        exit 0



  facade-service:
    container_name: facade-service
    build: ./facade-service
    ports:
      - "8000:8000"
    networks:
      - service-network
    environment:
      - SERVICE_NAME=facade-service
      - SERVICE_PORT=8000
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - HOSTNAME=facade-service
    depends_on:
      consul:
        condition: service_healthy

  logging-service-1:
    container_name: logging-service-1
    build: ./logging-service
    environment:
      - HZ_PORT=5701
      - HZ_IP= #
      - SERVICE_NAME=logging-service
      - SERVICE_PORT=8001
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      zookeeper-1:
        condition: service_healthy
      consul:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - service-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  logging-service-2:
    container_name: logging-service-2
    build: ./logging-service
    environment:
      - HZ_PORT=5702
      - HZ_IP= #
      - SERVICE_NAME=logging-service
      - SERVICE_PORT=8001
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "8002:8001"
    networks:
      - service-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  logging-service-3:
    container_name: logging-service-3
    build: ./logging-service
    environment:
      - HZ_PORT=5703
      - HZ_IP= #
      - SERVICE_NAME=logging-service
      - SERVICE_PORT=8001
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "8003:8001"
    networks:
      - service-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      
  messages-service-1:
    container_name: messages-service-1
    build: ./messages-service
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      zookeeper-1:
        condition: service_healthy    
      consul:
        condition: service_healthy
    environment:
      - SERVICE_NAME=messages-service
      - SERVICE_PORT=8005
      - HOSTNAME=messages-service-1
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - service-network
    ports:
      - "8005:8005"
 
  messages-service-2:
    container_name: messages-service-2
    build: ./messages-service
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      zookeeper-1:
        condition: service_healthy
      consul:
        condition: service_healthy
    environment:
      - SERVICE_NAME=messages-service
      - SERVICE_PORT=8005
      - HOSTNAME=messages-service-2
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - service-network
    ports:
      - "8006:8005"

  zookeeper-1:
    container_name: zookeeper-1
    image: confluentinc/cp-zookeeper:latest
    networks:
      - service-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: echo 123
      interval: 10s
      timeout: 5s
      retries: 3


  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - "9093:9093"
    networks:
      - service-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 2
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-1:9092 --list
      interval: 10s
      timeout: 5s
      retries: 3

  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - "9094:9094"
    networks:
      - service-network
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 2
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-2:9092 --list
      interval: 10s
      timeout: 5s
      retries: 3

  kafka-3:
    container_name: kafka-3
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - "9095:9095"
    networks:
      - service-network
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 2
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-3:9092 --list
      interval: 10s
      timeout: 5s
      retries: 3

  kafka-topic-creator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    entrypoint: [
      "bash", "-c",
      "sleep 10 && kafka-topics --bootstrap-server kafka-1:9092,kafka-2:9092,kafka-3:9092 --create --topic messages --partitions 3 --replication-factor 3"
    ]
    networks:
      - service-network


networks:
  service-network:
    name: service-network